// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8k-LoQHNt9wJ1KSq3KCdhxoNgkdxDDE4',
    appId: '1:316684711116:web:da9dae2e1e96b3e9a4fe69',
    messagingSenderId: '316684711116',
    projectId: 'takamo-6b453',
    authDomain: 'takamo-6b453.firebaseapp.com',
    storageBucket: 'takamo-6b453.appspot.com',
    measurementId: 'G-VV2P3M3NCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxA3_FN32m0oHELQUlFFyFKTcHjjPpbHk',
    appId: '1:316684711116:android:82b58a410d956b68a4fe69',
    messagingSenderId: '316684711116',
    projectId: 'takamo-6b453',
    storageBucket: 'takamo-6b453.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkF9h_sV2dWcfBCD_9_u1PfTW0f4Hhaec',
    appId: '1:316684711116:ios:88d28d630e048cc1a4fe69',
    messagingSenderId: '316684711116',
    projectId: 'takamo-6b453',
    storageBucket: 'takamo-6b453.appspot.com',
    iosClientId: '316684711116-hssec3bj4ua67q05qcct58pirgf94hdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
